version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/downloading" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/authentik" 
    schedule:
      interval: "weekly"
