networks:
  internal:
    internal: true
  external:
    
services:
  epicgamesfreegames:
    image: charlocharlie/epicgames-freegames:latest
    volumes:
      - /mnt/user/appdata/epicgames-freegames:/usr/app/config
    networks:
      - external
    ports:
      - 3055:3000
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped
